name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - Wojtek
      - Slawek
      - Pati
  workflow_dispatch:

jobs:
  Android:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build Android
        run: dotnet build --no-restore

  iOS:
    runs-on: macOS-12

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build iOS
        run: dotnet build --no-restore

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build application
        run: dotnet build --no-restore
