name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - Wojtek
      - Slawek
      - Pati
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .Net Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with: 
          dotnet-version: 7.0.x
      - name: Setup Xamarin
        uses: maxim-lobanov/setup-xamarin@v1
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
